# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-31 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_ID', models.CharField(max_length=20)),
                ('Company_Name', models.CharField(max_length=20)),
                ('Company_Contact', models.CharField(max_length=20)),
                ('Tel', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_ID', models.CharField(max_length=20)),
                ('Employee_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price_True', models.IntegerField(default=0)),
                ('Amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_ID', models.CharField(max_length=20)),
                ('Order_Date', models.DateTimeField(auto_now_add=True)),
                ('Customer_ID', models.ManyToManyField(to='sema_member.Customers')),
                ('Employee_ID', models.ManyToManyField(to='sema_member.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='Product_kinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kind_ID', models.CharField(max_length=20)),
                ('Kind_Name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Products_ID', models.CharField(max_length=20)),
                ('Pd_Name', models.TextField(blank=True)),
                ('Price_Suggest', models.IntegerField(default=0)),
                ('Inventory', models.IntegerField(default=0)),
                ('Kind_ID', models.ManyToManyField(to='sema_member.Product_kinds')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_ID', models.CharField(max_length=20)),
                ('Supplier_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='Supplier_ID',
            field=models.ManyToManyField(to='sema_member.Suppliers'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='Order_ID',
            field=models.ManyToManyField(to='sema_member.Orders'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='Products_ID',
            field=models.ManyToManyField(to='sema_member.Products'),
        ),
    ]
