# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-20 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sema_member', '0002_chat1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat1',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_chats', to='sema_member.Employees'),
        ),
    ]
