# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-20 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sema_member', '0004_auto_20180820_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat1',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat1',
        ),
    ]
